apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.cloud "gcp" }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  {{- end }}
  name: {{ include "nexp-api.fullname" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nexp-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nexp-api.selectorLabels" . | nindent 4 }}
