{{- if eq .Values.cloud "gcp" }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-sa-external-secrets-sm
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  secret-access-credentials: {{ .Files.Get "files/gcp-credentials-external-secret.json" | b64enc }}
{{- end }}
